version: '3.4'

services:
  libraryadmin:
    image: ${DOCKER_REGISTRY-}libraryadmin
    depends_on:
     - "app_db"
    container_name: libadmin
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__LibraryAdminDbContext=User ID=postgres;Password=123;Server=app_db;Port=5432;Database=dbLibrary;
      #- LibraryAdminDbContext=User ID=postgres;Password=123;Port=5432;Database=dbLibrary;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dbLibrary
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
    app_data:









  