version: '3.4'

services:
  libraryadmin:
    image: ${DOCKER_REGISTRY-}libraryadmin
    depends_on:
     - "app_db"
    container_name: libadmin
    platform: linux/amd64
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  app_db:
    image: postgres:latest
    container_name: app_db
    platform: linux/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dbLibrary
    ports:
      - "5432:5432"
    restart: always
    #volumes:
    #  - app_data:/var/lib/postgresql/data
    #networks:
    #  - dev
#volumes:
#    app_data:









  